# Generated by Django 5.2.7 on 2025-11-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='نام فرم', max_length=200)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('share_link', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'فرم',
                'verbose_name_plural': 'فرم ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('email', 'ایمیل'), ('phone', 'موبایل'), ('date', 'تاریخ'), ('time', 'زمان'), ('checkbox', 'چند انتخابی'), ('dropdown', 'لیست کشویی'), ('file', 'فایل'), ('radio', 'انتخابی'), ('switch', 'دو گزینه ای'), ('slider', 'اسلایدر'), ('password', 'رمز'), ('url', 'لینک'), ('tag', 'تگ')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('order_index', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Form.formmodel')),
            ],
            options={
                'unique_together': {('form', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Form.formmodel', verbose_name='فرم مربوطه')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('response_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_fields', to='Form.fieldmodel')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='Form.response', verbose_name='پاسخ مربوطه')),
            ],
            options={
                'verbose_name': 'پاسخ فیلد',
                'verbose_name_plural': 'پاسخ فیلدها',
            },
        ),
    ]
