# Generated by Django 5.2.9 on 2025-12-24 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Form.formmodel', verbose_name='فرم مربوطه')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterField(
            model_name='fieldresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='Form.allresponse', verbose_name='پاسخ مربوطه'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
