# Generated by Django 5.2.7 on 2025-12-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_allresponse_alter_fieldresponse_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
