# Generated by Django 5.2.7 on 2026-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_alter_formmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldresponse',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='form_uploads/%Y/%m/%d/'),
        ),
    ]
