# Generated by Django 5.2.7 on 2026-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_fieldresponse_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmodel',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
