# Generated by Django 5.2.7 on 2026-06-24 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_formmodel_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='share_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
