# Generated by Django 5.2.7 on 2026-02-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_set_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
