# Generated by Django 5.2.9 on 2026-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_has_set_password_user_is_profile_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=11)),
                ('purpose', models.CharField(choices=[('reset_password', 'Reset password'), ('signup', 'Signup')], db_index=True, max_length=32)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneResetOTP',
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['mobile', 'purpose', '-created_at'], name='accounts_ph_mobile_6c55d2_idx'),
        ),
    ]
