# Generated by Django 5.2.7 on 2026-06-24 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers, and ./+/-/_ characters.', regex='^[\\w.+-]+$')]),
        ),
        migrations.AddConstraint(
            model_name='phoneotp',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('mobile', 'purpose'), name='unique_unused_otp_per_mobile_purpose'),
        ),
    ]
