# Generated by Django 5.2.7 on 2026-08-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_set_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_profile_completed',
        ),
    ]
